# reference: https://github.com/jeremad/cuda-travis/blob/master/.travis.yml
language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  - sudo apt update
  - sudo apt install -y software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt update
  - sudo apt install -y python3-pip python3.6 g++
  - pip3 install -U pip
  - pip3 install setuptools
  - pip3 install -r requirements.txt
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-curand-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-} 
  - sudo apt clean
  - export CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
  - python3.6 -m grpc_tools.protoc --python_out cuhnswplus/ --proto_path cuhnswplus/proto/ config.proto

script:
  - sudo python3.6 setup.py install
